# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ocrdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(534, 435)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_shot = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_shot.sizePolicy().hasHeightForWidth())
        self.label_shot.setSizePolicy(sizePolicy)
        self.label_shot.setText("")
        self.label_shot.setScaledContents(False)
        self.label_shot.setObjectName("label_shot")
        self.verticalLayout.addWidget(self.label_shot)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_text_translate = QtWidgets.QLabel(Dialog)
        self.label_text_translate.setObjectName("label_text_translate")
        self.gridLayout.addWidget(self.label_text_translate, 2, 0, 1, 1)
        self.edit_translate = QtWidgets.QTextEdit(Dialog)
        self.edit_translate.setObjectName("edit_translate")
        self.gridLayout.addWidget(self.edit_translate, 3, 0, 1, 1)
        self.label_text_ocr = QtWidgets.QLabel(Dialog)
        self.label_text_ocr.setObjectName("label_text_ocr")
        self.gridLayout.addWidget(self.label_text_ocr, 0, 0, 1, 1)
        self.edit_ocr = QtWidgets.QTextEdit(Dialog)
        self.edit_ocr.setObjectName("edit_ocr")
        self.gridLayout.addWidget(self.edit_ocr, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_continue = QtWidgets.QPushButton(Dialog)
        self.pushButton_continue.setObjectName("pushButton_continue")
        self.horizontalLayout_3.addWidget(self.pushButton_continue)
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_3.addWidget(self.pushButton_close)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_text_translate.setText(_translate("Dialog", "Translate:"))
        self.label_text_ocr.setText(_translate("Dialog", "OCR:"))
        self.pushButton_continue.setText(_translate("Dialog", "Continue"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
